"""Importing this package registers every tool.
Add one import line here for each new tool file."""
from app.modules.mathematics import algebra  # noqa: F401
from app.modules.mathematics import calculus  # noqa: F401
from app.modules.mathematics import linear_algebra  # noqa: F401
from app.modules.mathematics import numerical  # noqa: F401
from app.modules.mathematics import ode  # noqa: F401
from app.modules.mathematics import plotting  # noqa: F401
from app.modules.physics import elements  # noqa: F401
from app.modules.physics import orbital  # noqa: F401
from app.modules.physics import propagation  # noqa: F401
from app.modules.physics import classical  # noqa: F401
from app.modules.physics import propulsion  # noqa: F401
from app.modules.chemistry import acid_base  # noqa: F401
from app.modules.chemistry import equilibrium  # noqa: F401
from app.modules.chemistry import gas  # noqa: F401
from app.modules.chemistry import labbench  # noqa: F401
from app.modules.chemistry import kinetics  # noqa: F401
from app.modules.chemistry import stoichiometry  # noqa: F401
from app.modules.physics import circuits  # noqa: F401
from app.modules.physics import electrostatics  # noqa: F401
from app.modules.physics import optics  # noqa: F401
from app.modules.physics import waves  # noqa: F401
from app.modules.physics import ac_circuits  # noqa: F401
from app.modules.physics import collisions  # noqa: F401
from app.modules.physics import magnetism  # noqa: F401
from app.modules.physics import ramp  # noqa: F401
from app.modules.physics import track  # noqa: F401
from app.modules.chemistry import spectroscopy  # noqa: F401
from app.modules.chemistry import titration  # noqa: F401
from app.modules.chemistry import vsepr  # noqa: F401
from app.modules.chemistry import atoms  # noqa: F401
from app.modules.mathematics import dynamics  # noqa: F401
from app.modules.mathematics import trig_fourier  # noqa: F401
from app.modules.mathematics import vectors_prob  # noqa: F401
from app.modules.mathematics import approximation  # noqa: F401
from app.modules.mathematics import complex_linear  # noqa: F401
from app.modules.physics import modern  # noqa: F401
from app.modules.physics import thermo  # noqa: F401
from app.modules.chemistry import solutions  # noqa: F401
from app.modules.chemistry import electrochem  # noqa: F401
from app.modules.chemistry import real_gases  # noqa: F401
from app.modules.chemistry import energy_profile  # noqa: F401
from app.modules.physics import oscillations  # noqa: F401
from app.modules.physics import charged  # noqa: F401
from app.modules.physics import doppler  # noqa: F401
from app.modules.mathematics import curves  # noqa: F401
from app.modules.mathematics import fitting  # noqa: F401
from app.modules.mathematics import monte_carlo  # noqa: F401
from app.modules.mathematics import fractals  # noqa: F401
from app.modules.mathematics import graphs  # noqa: F401
from app.modules.physics import rotation  # noqa: F401
from app.modules.physics import fluids  # noqa: F401
from app.modules.physics import heat  # noqa: F401
from app.modules.physics import quantum  # noqa: F401
from app.modules.physics import kepler  # noqa: F401
from app.modules.chemistry import reactions  # noqa: F401
from app.modules.chemistry import speciation  # noqa: F401
from app.modules.chemistry import colligative  # noqa: F401
from app.modules.chemistry import dating  # noqa: F401
from app.modules.physics import perturbations  # noqa: F401
from app.modules.chemistry import phases  # noqa: F401
from app.modules.physics import ephemeris  # noqa: F401
from app.modules.physics import rocketry  # noqa: F401
from app.modules.physics import smallbodies  # noqa: F401
from app.modules.physics import universe  # noqa: F401
from app.modules.physics import skyatlas  # noqa: F401
from app.modules.physics import rocketdesign  # noqa: F401
from app.modules.physics import vehicles  # noqa: F401
from app.modules.physics import fleet  # noqa: F401
from app.modules.physics import interplanetary  # noqa: F401
from app.modules.teach import lab  # noqa: F401
from app.modules.teach import explore  # noqa: F401
from app.modules.teach import listen  # noqa: F401
from app.modules.physics import blackhole  # noqa: F401
from app.modules.physics import quantum_dynamics  # noqa: F401
