"""Importing this package registers every tool.
Add one import line here for each new tool file."""
from app.modules.mathematics import algebra  # noqa: F401
from app.modules.mathematics import calculus  # noqa: F401
from app.modules.mathematics import linear_algebra  # noqa: F401
from app.modules.mathematics import numerical  # noqa: F401
from app.modules.mathematics import ode  # noqa: F401
from app.modules.mathematics import plotting  # noqa: F401
from app.modules.physics import elements  # noqa: F401
from app.modules.physics import orbital  # noqa: F401
from app.modules.physics import propagation  # noqa: F401
from app.modules.physics import classical  # noqa: F401
from app.modules.physics import propulsion  # noqa: F401
from app.modules.chemistry import acid_base  # noqa: F401
from app.modules.chemistry import equilibrium  # noqa: F401
from app.modules.chemistry import gas  # noqa: F401
from app.modules.chemistry import kinetics  # noqa: F401
from app.modules.chemistry import stoichiometry  # noqa: F401
from app.modules.physics import circuits  # noqa: F401
from app.modules.physics import electrostatics  # noqa: F401
from app.modules.physics import optics  # noqa: F401
from app.modules.physics import waves  # noqa: F401
from app.modules.physics import ac_circuits  # noqa: F401
from app.modules.physics import collisions  # noqa: F401
from app.modules.physics import magnetism  # noqa: F401
from app.modules.physics import ramp  # noqa: F401
from app.modules.physics import track  # noqa: F401
from app.modules.chemistry import spectroscopy  # noqa: F401
from app.modules.chemistry import titration  # noqa: F401
from app.modules.chemistry import vsepr  # noqa: F401
from app.modules.chemistry import atoms  # noqa: F401
from app.modules.mathematics import dynamics  # noqa: F401
from app.modules.mathematics import trig_fourier  # noqa: F401
from app.modules.mathematics import vectors_prob  # noqa: F401
